<?php

namespace AppBundle\Repository;

/**
 * ftaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ftaskRepository extends \Doctrine\ORM\EntityRepository
{
}
